### ISSUE TITLE
User Defined Packages Are Shown As Unresolved References

### ISSUE THREAD

**Issue by moizalicious** [ballerina-lang/plugin-intellij#798]
I have a package called `src.test` which has the file `Foo.bal` which contains the following ballerina code:
```ballerina
package src.test;

public function foo() {
    println("Hello World");
}
```

The IDE cannot seem to identify the `src.test` package and marks it as an error when I try to use it in another file of a different package or in the root folder:
![screenshot from 2018-01-26 16-16-10](https://user-images.githubusercontent.com/25219255/35436418-647c49b2-02b4-11e8-918a-70125fa99058.png)

When I run the above `Main.bal` file, the program runs with no errors:
![image](https://user-images.githubusercontent.com/25219255/35436263-c0c1de90-02b3-11e8-9401-470966b66ba0.png)

**_Using Ballerina 0.95.8_**

**Comment by Shan1024** [comment]
@moizalicious - Can you also send a screenshot of the project structure?

**Comment by moizalicious** [comment]
Hi @Shan1024,
This is the project structure I have used for the above example:
![image](https://user-images.githubusercontent.com/25219255/35564536-85e0138e-05e0-11e8-886d-16171fab71b3.png)
